<?php
/**
 * GreenPure CBD — Données démo
 * Crée automatiquement les catégories + produits de démonstration.
 *
 * Utilisation : ajouter ?greenpure_install_demo=1 dans l'URL une fois
 * connecté en admin, ou appeler greenpure_install_demo_products() directement.
 *
 * SUPPRIMER ce fichier en production si vous ne voulez plus les données démo.
 */
defined('ABSPATH') || exit;

/* ──────────────────────────────────────────────
   Déclencheur URL : ?greenpure_install_demo=1
────────────────────────────────────────────── */
add_action('init', function () {
    if (
        isset($_GET['greenpure_install_demo']) &&
        current_user_can('manage_woocommerce') &&
        class_exists('WooCommerce')
    ) {
        greenpure_install_demo_products();
        wp_redirect(admin_url('edit.php?post_type=product&greenpure_demo=ok'));
        exit;
    }
});

/* ──────────────────────────────────────────────
   Auto-install sur activation du thème
────────────────────────────────────────────── */
add_action('after_switch_theme', function () {
    if (class_exists('WooCommerce')) {
        greenpure_install_demo_products();
    }
});

/* ──────────────────────────────────────────────
   Auto-install via admin_init si aucun produit
────────────────────────────────────────────── */
add_action('admin_init', function () {
    if (!class_exists('WooCommerce')) return;
    if (get_option('greenpure_demo_auto_installed')) return;

    $count = wp_count_posts('product');
    $total = ($count->publish ?? 0) + ($count->draft ?? 0) + ($count->private ?? 0);

    if ($total === 0) {
        greenpure_install_demo_products();
        update_option('greenpure_demo_auto_installed', '1');
    } else {
        update_option('greenpure_demo_auto_installed', '1');
    }
});

/* ──────────────────────────────────────────────
   FONCTION PRINCIPALE
────────────────────────────────────────────── */
function greenpure_install_demo_products() {
    if (! class_exists('WooCommerce')) return;

    /* ---- Catégories ---- */
    $cats = [
        'huiles-cbd'    => ['name' => 'Huiles CBD',         'desc' => 'Huiles CBD full et broad spectrum de haute qualité.'],
        'fleurs-cbd'    => ['name' => 'Fleurs CBD',          'desc' => 'Fleurs CBD bio, séchées à froid, < 0,2 % THC.'],
        'gummies-cbd'   => ['name' => 'Gummies CBD',         'desc' => 'Gommes CBD vegan, sans sucre ajouté.'],
        'cosmetiques'   => ['name' => 'Cosmétiques CBD',     'desc' => 'Crèmes, baumes et sérums au CBD.'],
        'infusions-cbd' => ['name' => 'Infusions CBD',       'desc' => 'Tisanes aux plantes enrichies en CBD.'],
        'capsules-cbd'  => ['name' => 'Capsules CBD',        'desc' => 'Capsules dosées avec précision pour la routine quotidienne.'],
        'e-liquides'    => ['name' => 'E-liquides CBD',      'desc' => 'E-liquides CBD pour cigarettes électroniques, bases 50/50.'],
    ];

    $cat_ids = [];
    foreach ($cats as $slug => $data) {
        $existing = get_term_by('slug', $slug, 'product_cat');
        if ($existing) {
            $cat_ids[$slug] = $existing->term_id;
        } else {
            $term = wp_insert_term($data['name'], 'product_cat', [
                'slug'        => $slug,
                'description' => $data['desc'],
            ]);
            $cat_ids[$slug] = is_wp_error($term) ? 0 : $term['term_id'];
        }
    }

    /* ---- Produits ---- */
    $products = [

        /* ══════════════ HUILES CBD ══════════════ */
        [
            'name'        => 'Huile CBD Full Spectrum 5% — 10ml',
            'sku'         => 'GP-HFS-05',
            'price'       => '19.90',
            'sale'        => '14.90',
            'cat'         => 'huiles-cbd',
            'featured'    => true,
            'short_desc'  =>  "Idéale pour les débutants. Extraction CO₂ supercritique, huile MCT bio.",
            'description' =>  "<p>Notre huile CBD Full Spectrum 5% est le point d'entrée parfait pour découvrir les bienfaits du CBD. Formulée à partir de chanvre bio cultivé en France, extraite par CO₂ supercritique pour préserver tous les cannabinoïdes et terpènes naturels.</p><ul><li>Concentration : 500 mg CBD / 10 ml</li><li>Spectre : Full Spectrum (&lt; 0,2 % THC)</li><li>Base : Huile MCT de noix de coco bio</li><li>Origine chanvre : France</li></ul>",
            'cbd_concentration' => '5%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 150,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Full Spectrum 10% — 10ml',
            'sku'         => 'GP-HFS-10',
            'price'       => '34.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => true,
            'short_desc'  =>  "Notre best-seller. 1000 mg CBD, spectre complet, base MCT bio.",
            'description' =>  "<p>La Huile CBD Full Spectrum 10% est notre produit phare. Avec 1000 mg de CBD par flacon, elle offre un excellent rapport qualité-prix pour une utilisation quotidienne.</p><ul><li>Concentration : 1000 mg CBD / 10 ml</li><li>Spectre : Full Spectrum (&lt; 0,2 % THC)</li><li>Base : Huile MCT de noix de coco bio</li><li>Certifié labo ISO 17025</li></ul>",
            'cbd_concentration' => '10%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 200,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Full Spectrum 20% — 10ml',
            'sku'         => 'GP-HFS-20',
            'price'       => '59.90',
            'sale'        => '54.90',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "Haute concentration pour utilisateurs avancés. 2000 mg CBD / 10 ml.",
            'description' =>  "<p>Notre formule haute concentration pour les utilisateurs expérimentés cherchant un effet puissant. 2000 mg de CBD pur par flacon, extraction premium.</p>",
            'cbd_concentration' => '20%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'Suisse',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 80,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Broad Spectrum 10% — 10ml',
            'sku'         => 'GP-HBS-10',
            'price'       => '29.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "Sans THC détectable. Idéale pour les sportifs soumis à des contrôles.",
            'description' =>  "<p>La Huile CBD Broad Spectrum 10% contient tous les cannabinoïdes bénéfiques sauf le THC, qui est rigoureusement éliminé par chromatographie. Parfaite pour les sportifs de haut niveau.</p>",
            'cbd_concentration' => '10%',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ + Chromatographie',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 120,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Sommeil 15% + Mélatonine — 10ml',
            'sku'         => 'GP-HSM-15',
            'price'       => '44.90',
            'sale'        => '39.90',
            'cat'         => 'huiles-cbd',
            'featured'    => true,
            'short_desc'  =>  "CBD 15% + mélatonine + lavande. Formulée pour favoriser un endormissement rapide.",
            'description' =>  "<p>Notre formule Sommeil exclusive associe 1500 mg de CBD Full Spectrum à 1 mg de mélatonine par dose et de l'huile essentielle de lavande vraie. Idéale 30 min avant le coucher.</p>",
            'cbd_concentration' => '15%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 90,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Sport Recovery 10% — 10ml',
            'sku'         => 'GP-HSP-10',
            'price'       => '39.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD + omega-3 + vitamine D. Spécialement formulée pour la récupération musculaire.",
            'description' =>  "<p>La formule Sport Recovery combine 1000 mg de CBD Broad Spectrum avec des oméga-3 issus de lin bio et de la vitamine D3. Conçue pour les sportifs qui souhaitent optimiser leur récupération.</p>",
            'cbd_concentration' => '10%',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 100,
            'weight'     => '0.05',
        ],

        /* ══════════════ FLEURS CBD ══════════════ */
        [
            'name'        => 'Fleurs CBD OG Kush Indoor — 3g',
            'sku'         => 'GP-FOG-3',
            'price'       => '12.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => true,
            'short_desc'  =>  "Arômes terreux et citronnés, effet relaxant. CBD ~18%, THC < 0,2%.",
            'description' =>  "<p>La OG Kush CBD Indoor est cultivée en intérieur sous LED à spectre complet. Arômes complexes de citron, de pin et de terre. Trichomes abondants, cure de 4 semaines minimale.</p>",
            'cbd_concentration' => '~18%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 300,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD Amnesia Haze Indoor — 3g',
            'sku'         => 'GP-FAH-3',
            'price'       => '11.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Arômes citronnés et épicés, goût fruité, effet stimulant et créatif.",
            'description' =>  "<p>L\'Amnesia Haze CBD est une sativa à dominance qui offre des arômes citronnés et épicés remarquables. Parfaite pour la journée, elle favorise la concentration et la créativité.</p>",
            'cbd_concentration' => '~16%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Espagne',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 250,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD Critical+ Greenhouse — 5g',
            'sku'         => 'GP-FCG-5',
            'price'       => '15.90',
            'sale'        => '12.90',
            'cat'         => 'fleurs-cbd',
            'featured'    => true,
            'short_desc'  =>  "Cultivée en serre bioclimatique. Arômes fruités et sucrés, CBD ~14%.",
            'description' =>  "<p>La Critical+ CBD Greenhouse est produite en serre bioclimatique, bénéficiant de la lumière naturelle. Arômes fruités, sucrés, légèrement épicés. Rendement élevé en CBD.</p>",
            'cbd_concentration' => '~14%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Greenhouse Suisse',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 400,
            'weight'     => '0.005',
        ],
        [
            'name'        => 'Fleurs CBD Purple Haze Indoor — 3g',
            'sku'         => 'GP-FPH-3',
            'price'       => '13.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Teintes violettes, arômes de fruits rouges et raisin. CBD ~15%.",
            'description' =>  "<p>La Purple Haze CBD est une variété remarquable par ses teintes violettes et son profil aromatique unique de fruits rouges et de raisin. Cultivation indoor de qualité supérieure.</p>",
            'cbd_concentration' => '~15%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Pays-Bas',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 180,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD White Widow Outdoor Bio — 5g',
            'sku'         => 'GP-FWW-5',
            'price'       => '9.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Culture outdoor bio certifiée. Arômes de bois et d\'épices, très résineuse.",
            'description' =>  "<p>La White Widow CBD Outdoor Bio est certifiée agriculture biologique. Cultivée en plein air sans pesticides ni herbicides. Arômes de bois, de terre et d\'épices avec une résine abondante.</p>",
            'cbd_concentration' => '~12%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Outdoor France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 500,
            'weight'     => '0.005',
        ],

        /* ══════════════ GUMMIES CBD ══════════════ */
        [
            'name'        => 'Gummies CBD Relaxation — 25mg x10',
            'sku'         => 'GP-GRX-10',
            'price'       => '24.90',
            'sale'        => '',
            'cat'         => 'gummies-cbd',
            'featured'    => true,
            'short_desc'  =>  "Gommes vegan goût fruits tropicaux. 250mg CBD Broad Spectrum par boîte.",
            'description' =>  "<p>Nos Gummies CBD Relaxation sont formulées avec du CBD Broad Spectrum de qualité pharmaceutique. 100% vegan, sans gélatine animale, goût fruits tropicaux naturels. Sans sucre ajouté, sucrées à l'érythritol.</p><ul><li>25 mg CBD par gomme</li><li>Boîte de 10 gommes (250 mg total)</li><li>Vegan | Sans gluten | Sans sucre ajouté</li></ul>",
            'cbd_concentration' => '25mg/gomme',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 200,
            'weight'     => '0.08',
        ],
        [
            'name'        => 'Gummies CBD Sommeil + Mélatonine — 25mg x10',
            'sku'         => 'GP-GSM-10',
            'price'       => '27.90',
            'sale'        => '22.90',
            'cat'         => 'gummies-cbd',
            'featured'    => true,
            'short_desc'  =>  "CBD 25mg + 1mg mélatonine + passiflore. Goût cerise-lavande.",
            'description' =>  "<p>Les Gummies Sommeil associent 25 mg de CBD Broad Spectrum à 1 mg de mélatonine et de l'extrait de passiflore par gomme. Saveur cerise-lavande apaisante. À prendre 30 min avant le coucher.</p>",
            'cbd_concentration' => '25mg/gomme',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 150,
            'weight'     => '0.08',
        ],
        [
            'name'        => 'Gummies CBD Multivitamines — 10mg x30',
            'sku'         => 'GP-GMV-30',
            'price'       => '34.90',
            'sale'        => '',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD + vitamines B, C, D3, zinc. Pour le bien-être quotidien.",
            'description' =>  "<p>Les Gummies CBD Multivitamines combinent 10 mg de CBD Isolat avec un complexe vitaminique complet (B1, B6, B12, C, D3, E, zinc, magnésium). Goût orange naturel. Format 30 gommes pour un mois de cure.</p>",
            'cbd_concentration' => '10mg/gomme',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 120,
            'weight'     => '0.15',
        ],
        [
            'name'        => 'Gummies CBD Anti-Stress Ashwagandha — 20mg x15',
            'sku'         => 'GP-GAS-15',
            'price'       => '29.90',
            'sale'        => '24.90',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 20mg + ashwagandha KSM-66 + L-théanine. Goût pomme verte.",
            'description' =>  "<p>Notre formule Anti-Stress associe 20 mg de CBD à 300 mg d'ashwagandha KSM-66 (breveté) et 100 mg de L-théanine pour un effet adaptogène maximal. Parfait pour les périodes de stress intense.</p>",
            'cbd_concentration' => '20mg/gomme',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 180,
            'weight'     => '0.10',
        ],

        /* ══════════════ COSMÉTIQUES ══════════════ */
        [
            'name'        => 'Crème CBD Anti-Douleur 500mg — 50ml',
            'sku'         => 'GP-CAD-50',
            'price'       => '28.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => true,
            'short_desc'  =>  "Crème chauffante au CBD, arnica et camphre. Soulage muscles et articulations.",
            'description' =>  "<p>Notre crème anti-douleur associe 500 mg de CBD Isolat à de l'arnica montana, du camphre naturel et de l'huile essentielle d'eucalyptus. Texture chauffante, absorption rapide.</p><ul><li>500 mg CBD Isolat / 50 ml</li><li>Arnica Montana BIO</li><li>Sans parabènes | Vegan | Testé dermatologiquement</li></ul>",
            'cbd_concentration' => '500mg/50ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 90,
            'weight'     => '0.12',
        ],
        [
            'name'        => 'Baume CBD Muscles & Articulations 300mg — 60ml',
            'sku'         => 'GP-BMA-60',
            'price'       => '24.90',
            'sale'        => '19.90',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Baume solide CBD + beurre de karité + menthol. Idéal avant / après sport.",
            'description' =>  "<p>Le Baume Muscles & Articulations au CBD est formulé avec du beurre de karité bio, de l'huile de coco et du menthol naturel. Application ciblée sur les zones douloureuses.</p>",
            'cbd_concentration' => '300mg/60ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 120,
            'weight'     => '0.10',
        ],
        [
            'name'        => 'Sérum CBD Anti-Âge 200mg — 30ml',
            'sku'         => 'GP-SAA-30',
            'price'       => '39.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => true,
            'short_desc'  =>  "CBD + acide hyaluronique + vitamine C. Texture légère, anti-rides.",
            'description' =>  "<p>Le Sérum Anti-Âge associe 200 mg de CBD à de l'acide hyaluronique pur (2 poids moléculaires), de la vitamine C stabilisée et du rétinol végétal. Texture sérum légère, absorption immédiate.</p>",
            'cbd_concentration' => '200mg/30ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 70,
            'weight'     => '0.06',
        ],
        [
            'name'        => 'Masque Visage CBD Purifiant 100mg — 75ml',
            'sku'         => 'GP-MVC-75',
            'price'       => '19.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Masque argile + CBD + aloe vera. Purifie, resserre les pores, hydrate.",
            'description' =>  "<p>Le Masque Visage au CBD combine argile verte, aloe vera bio et 100 mg de CBD Isolat. Purifie en profondeur, resserre les pores dilatés et apporte une hydratation intense.</p>",
            'cbd_concentration' => '100mg/75ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 100,
            'weight'     => '0.15',
        ],

        /* ══════════════ INFUSIONS ══════════════ */
        [
            'name'        => 'Infusion CBD Relaxante Camomille — 20 sachets',
            'sku'         => 'GP-IRC-20',
            'price'       => '16.90',
            'sale'        => '',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Camomille, tilleul et fleurs de chanvre CBD. Apaisante et douce.",
            'description' =>  "<p>Notre infusion Relaxante associe de la camomille matricaire, du tilleul argenté et des fleurs de chanvre CBD broyées. Sans théine, à consommer le soir pour un effet relaxant optimal.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 200,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Infusion CBD Sommeil Lavande-Valériane — 20 sachets',
            'sku'         => 'GP-ISL-20',
            'price'       => '16.90',
            'sale'        => '13.90',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Lavande, valériane et chanvre CBD. Favorise l'endormissement naturellement.",
            'description' =>  "<p>Cette infusion Sommeil associe lavande officinale, racine de valériane et fleurs de chanvre CBD pour un cocktail de plantes reconnu pour favoriser le sommeil. Sans accoutumance.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 180,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Infusion CBD Énergie Gingembre-Menthe — 20 sachets',
            'sku'         => 'GP-IEG-20',
            'price'       => '14.90',
            'sale'        => '',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Gingembre, menthe poivrée et chanvre CBD. Tonifiante et stimulante.",
            'description' =>  "<p>L'infusion Énergie mêle gingembre frais, menthe poivrée et fleurs de chanvre CBD pour un réveil tout en douceur et une journée pleine d'énergie. Idéale le matin.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 160,
            'weight'     => '0.04',
        ],

        /* ══════════════ CAPSULES CBD ══════════════ */
        [
            'name'        => 'Capsules CBD 10mg — x30',
            'sku'         => 'GP-C10-30',
            'price'       => '29.90',
            'sale'        => '',
            'cat'         => 'capsules-cbd',
            'featured'    => false,
            'short_desc'  =>  "Capsules CBD Isolat 10mg, enveloppe végétale. Dosage précis, discret.",
            'description' =>  "<p>Nos capsules CBD 10 mg offrent un dosage précis et une prise pratique. Enveloppe végétale HPMC (vegan), CBD Isolat dissous dans de l'huile d'olive extra-vierge bio.</p>",
            'cbd_concentration' => '10mg/capsule',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 130,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Capsules CBD 20mg — x30',
            'sku'         => 'GP-C20-30',
            'price'       => '44.90',
            'sale'        => '39.90',
            'cat'         => 'capsules-cbd',
            'featured'    => true,
            'short_desc'  =>  "Capsules CBD Broad Spectrum 20mg. Effet entourage, sans THC.",
            'description' =>  "<p>Les capsules CBD 20 mg Broad Spectrum proposent un spectre élargi de cannabinoïdes (CBC, CBG, CBN) sans THC. Idéales pour une cure quotidienne efficace.</p>",
            'cbd_concentration' => '20mg/capsule',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 100,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Capsules CBD 30mg Full Spectrum — x30',
            'sku'         => 'GP-C30-30',
            'price'       => '59.90',
            'sale'        => '',
            'cat'         => 'capsules-cbd',
            'featured'    => false,
            'short_desc'  =>  "Haute dose Full Spectrum 30mg. Pour utilisateurs expérimentés.",
            'description' =>  "<p>Nos capsules haute dose 30 mg Full Spectrum sont destinées aux utilisateurs ayant déjà intégré le CBD dans leur routine. Maximum d'effet entourage avec tous les cannabinoïdes naturels.</p>",
            'cbd_concentration' => '30mg/capsule',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 60,
            'weight'     => '0.05',
        ],

        /* ══════════════ HUILES CBD (suite) ══════════════ */
        [
            'name'        => 'Huile CBD Isolat 5% — 10ml',
            'sku'         => 'GP-HIS-05',
            'price'       => '17.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD Isolat 99% pur, sans aucun autre cannabinoïde. Base MCT bio.",
            'description' =>  "<p>L'huile CBD Isolat 5% est fabriquée à partir de CBD isolé à 99 % de pureté. Idéale pour ceux qui souhaitent éviter tout autre cannabinoïde ou terpène. Goût neutre, parfaite sous la langue ou en cuisine.</p><ul><li>500 mg CBD Isolat / 10 ml</li><li>THC : 0,00 %</li><li>Base : Huile MCT bio</li></ul>",
            'cbd_concentration' => '5%',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 140,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Full Spectrum 30% — 10ml',
            'sku'         => 'GP-HFS-30',
            'price'       => '89.90',
            'sale'        => '79.90',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "Ultra-concentrée 3000 mg CBD. Réservée aux utilisateurs expérimentés.",
            'description' =>  "<p>Notre huile Full Spectrum 30% est la concentration maximale de notre gamme. 3000 mg de CBD par flacon de 10 ml, extraction CO₂ supercritique premium. Chaque pipette = 150 mg CBD. À utiliser avec précaution.</p>",
            'cbd_concentration' => '30%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'Suisse',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 40,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD + CBG 10% — 10ml',
            'sku'         => 'GP-HCG-10',
            'price'       => '42.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => true,
            'short_desc'  =>  "Synergie CBD + CBG pour focus et clarté mentale. Spectre enrichi.",
            'description' =>  "<p>L'huile CBD+CBG 10% combine 500 mg de CBD et 500 mg de CBG pour exploiter la synergie entre ces deux cannabinoïdes. Le CBG (cannabigérol) est reconnu pour ses propriétés neuroprotectrices et son effet stimulant sur la concentration.</p>",
            'cbd_concentration' => '10% (CBD+CBG)',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 75,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Full Spectrum 10% — 30ml',
            'sku'         => 'GP-HFS-10-30',
            'price'       => '74.90',
            'sale'        => '64.90',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "Grand format économique 3000 mg CBD. Idéal pour cure longue durée.",
            'description' =>  "<p>Le grand format 30 ml de notre huile Full Spectrum 10% offre 3000 mg de CBD pour une cure de 3 mois. Un choix économique pour les utilisateurs réguliers. Même formule que notre best-seller en format standard.</p>",
            'cbd_concentration' => '10%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 60,
            'weight'     => '0.10',
        ],
        [
            'name'        => 'Huile CBD Stress & Anxiété 15% — 10ml',
            'sku'         => 'GP-HAN-15',
            'price'       => '49.90',
            'sale'        => '44.90',
            'cat'         => 'huiles-cbd',
            'featured'    => true,
            'short_desc'  =>  "CBD 15% + L-théanine + safran. Formule anti-stress cliniquement étudiée.",
            'description' =>  "<p>Notre huile Stress & Anxiété associe 1500 mg de CBD Full Spectrum à de la L-théanine (200 mg/dose) et de l'extrait de safran standardisé en safranal. Cette triplette synergique favorise la sérénité sans somnolence.</p>",
            'cbd_concentration' => '15%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 85,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Huile CBD Animaux 2% — 10ml',
            'sku'         => 'GP-HAN-2-PET',
            'price'       => '22.90',
            'sale'        => '',
            'cat'         => 'huiles-cbd',
            'featured'    => false,
            'short_desc'  =>  "Spécialement formulée pour chiens et chats. Base huile de saumon sauvage.",
            'description' =>  "<p>L'huile CBD Animaux 2% est conçue pour les animaux de compagnie. Base d'huile de saumon sauvage (oméga-3 naturels) appréciée des chiens et des chats. CBD Isolat pur, 0,00 % THC. Dosage sécurisé pour les petits gabarits.</p><ul><li>200 mg CBD Isolat / 10 ml</li><li>THC : 0,00 %</li><li>Saveur : saumon naturel</li></ul>",
            'cbd_concentration' => '2%',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 110,
            'weight'     => '0.05',
        ],

        /* ══════════════ FLEURS CBD (suite) ══════════════ */
        [
            'name'        => 'Fleurs CBD Gorilla Glue Indoor — 3g',
            'sku'         => 'GP-FGG-3',
            'price'       => '14.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => true,
            'short_desc'  =>  "Variété ultra-résineuse, arômes de chocolat et de café. CBD ~20%.",
            'description' =>  "<p>La Gorilla Glue CBD Indoor est réputée pour sa production exceptionnelle de résine et ses arômes complexes de chocolat, de café et de pin. Cultivation indoor intensive sous LED 720W. Trichomes très denses.</p>",
            'cbd_concentration' => '~20%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Espagne',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 220,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD Lemon Haze Indoor — 3g',
            'sku'         => 'GP-FLH-3',
            'price'       => '12.90',
            'sale'        => '10.90',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Arômes citron vif et menthe, sativa énergisante. CBD ~17%.",
            'description' =>  "<p>La Lemon Haze CBD propose des arômes d'agrumes éclatants — citron frais, lime et touche de menthe. Profil terpénique riche en limonène. Cultivation indoor en hydroponie, floraison 8 semaines.</p>",
            'cbd_concentration' => '~17%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Pays-Bas',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 280,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD Gelato Indoor — 3g',
            'sku'         => 'GP-FGL-3',
            'price'       => '15.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => true,
            'short_desc'  =>  "Saveurs de dessert — vanille, fruits rouges, crème. CBD ~19%.",
            'description' =>  "<p>La Gelato CBD Indoor est une variété d'exception aux arômes gourmands de vanille, de fruits rouges et de crème glacée. L'un des profils de saveur les plus recherchés du marché CBD. Trichomes argentés et densité exceptionnelle.</p>",
            'cbd_concentration' => '~19%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Italie',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 170,
            'weight'     => '0.003',
        ],
        [
            'name'        => 'Fleurs CBD Blue Dream Greenhouse — 5g',
            'sku'         => 'GP-FBD-5',
            'price'       => '16.90',
            'sale'        => '13.90',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Arômes de myrtille et de vanille. Equilibrée, légèrement relaxante. CBD ~13%.",
            'description' =>  "<p>La Blue Dream CBD Greenhouse est cultivée en serre bioclimatique au Portugal. Ses arômes de myrtille sucrée et de vanille sont reconnaissables entre tous. Profil équilibré indiqué-sativa, parfaite pour la journée.</p>",
            'cbd_concentration' => '~13%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Greenhouse Portugal',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 350,
            'weight'     => '0.005',
        ],
        [
            'name'        => 'Fleurs CBD Strawberry Kush Outdoor Bio — 10g',
            'sku'         => 'GP-FSK-10',
            'price'       => '19.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Format économique 10g. Culture outdoor bio, arômes fraise-kush. CBD ~11%.",
            'description' =>  "<p>La Strawberry Kush CBD en format 10g est notre offre grand format outdoor bio. Arômes de fraise mûre et notes terreuses caractéristiques du Kush. Idéale pour les consommateurs réguliers qui cherchent un rapport qualité-prix optimal.</p>",
            'cbd_concentration' => '~11%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Outdoor France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 600,
            'weight'     => '0.010',
        ],
        [
            'name'        => 'Fleurs CBD Cheese Indoor — 5g',
            'sku'         => 'GP-FCH-5',
            'price'       => '18.90',
            'sale'        => '15.90',
            'cat'         => 'fleurs-cbd',
            'featured'    => false,
            'short_desc'  =>  "Arômes fromage, notes terreuses et épicées uniques. CBD ~16%.",
            'description' =>  "<p>La Cheese CBD Indoor est une variété iconique aux arômes puissants et distinctifs de fromage affiné, de terre et d'épices. Profil terpénique dominant myrcène et caryophyllène. Cultivation indoor sur substrat coco.</p>",
            'cbd_concentration' => '~16%',
            'cbd_spectrum'      => 'Fleur séchée',
            'cbd_extraction'    => 'N/A',
            'cbd_origin'        => 'Indoor Suisse',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 240,
            'weight'     => '0.005',
        ],
        [
            'name'        => 'Hash CBD Pollen Marocain — 2g',
            'sku'         => 'GP-HPM-2',
            'price'       => '18.90',
            'sale'        => '',
            'cat'         => 'fleurs-cbd',
            'featured'    => true,
            'short_desc'  =>  "Résine de chanvre CBD pressée à froid, style pollen. CBD ~35%, THC < 0,2%.",
            'description' =>  "<p>Notre Hash CBD Pollen est fabriqué par pressage à froid de trichomes de chanvre CBD sélectionné. Couleur dorée, consistance souple, arômes intenses de spice et de résine. THC &lt; 0,2 %, CBD ~35%.</p><ul><li>~700 mg CBD / 2g</li><li>Pressé à froid — sans solvant</li><li>Conditionnement sous vide</li></ul>",
            'cbd_concentration' => '~35%',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'Pressage à froid',
            'cbd_origin'        => 'Maroc / Espagne (sélection)',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 150,
            'weight'     => '0.002',
        ],

        /* ══════════════ GUMMIES CBD (suite) ══════════════ */
        [
            'name'        => 'Gummies CBD Immunité Zinc + Vitamine C — 10mg x20',
            'sku'         => 'GP-GIM-20',
            'price'       => '24.90',
            'sale'        => '',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 10mg + zinc + vitamine C. Soutien immunitaire quotidien. Goût citron.",
            'description' =>  "<p>Les Gummies CBD Immunité associent 10 mg de CBD Isolat à du zinc bisglycinate (10 mg), de la vitamine C naturelle (500 mg) et de la propolis bio. Saveur citron acidulée, sans sucre ajouté, sucrées à la stévia.</p>",
            'cbd_concentration' => '10mg/gomme',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 160,
            'weight'     => '0.10',
        ],
        [
            'name'        => 'Gummies CBD Focus Bacopa — 15mg x20',
            'sku'         => 'GP-GFO-20',
            'price'       => '27.90',
            'sale'        => '22.90',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 15mg + bacopa monnieri + huperzine A. Concentration et mémoire.",
            'description' =>  "<p>Les Gummies Focus associent 15 mg de CBD Broad Spectrum à 150 mg de bacopa monnieri standardisé (20% bacosides) et 100 µg d'huperzine A pour une synergie nootropique. Goût pomme-raisin.</p>",
            'cbd_concentration' => '15mg/gomme',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 130,
            'weight'     => '0.10',
        ],
        [
            'name'        => 'Gummies CBD Sport Récupération — 25mg x10',
            'sku'         => 'GP-GSR-10',
            'price'       => '29.90',
            'sale'        => '',
            'cat'         => 'gummies-cbd',
            'featured'    => true,
            'short_desc'  =>  "CBD 25mg + magnésium + BCAA végétaux. Pour la récupération musculaire.",
            'description' =>  "<p>Les Gummies Sport Récupération combinent 25 mg de CBD Broad Spectrum avec du magnésium bisglycinate (200 mg) et un complexe BCAA végétal. Idéales dans l'heure suivant l'entraînement. Saveur pastèque-menthe.</p>",
            'cbd_concentration' => '25mg/gomme',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 110,
            'weight'     => '0.08',
        ],
        [
            'name'        => 'Gummies CBD Beauté Collagène — 10mg x30',
            'sku'         => 'GP-GBC-30',
            'price'       => '36.90',
            'sale'        => '29.90',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 10mg + collagène marin + biotine + acide hyaluronique. Peau, cheveux, ongles.",
            'description' =>  "<p>Les Gummies Beauté Collagène sont formulées pour la beauté de l'intérieur : 10 mg CBD Isolat, 2500 mg collagène marin hydrolysé (type I & III), 5000 µg de biotine et 120 mg d'acide hyaluronique par dose journalière. Saveur fraise-pêche.</p>",
            'cbd_concentration' => '10mg/gomme',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 90,
            'weight'     => '0.15',
        ],
        [
            'name'        => 'Gummies CBD Énergie Maca + B12 — 15mg x20',
            'sku'         => 'GP-GEN-20',
            'price'       => '25.90',
            'sale'        => '',
            'cat'         => 'gummies-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 15mg + maca péruvienne + vitamine B12. Vitalité et tonus. Goût mangue.",
            'description' =>  "<p>Les Gummies Énergie associent 15 mg de CBD Isolat à 500 mg de maca péruvienne jaune (6:1) et 1000 µg de vitamine B12 méthylcobalamine. Un trio pour combattre la fatigue et retrouver de la vitalité. Saveur mangue-passion.</p>",
            'cbd_concentration' => '15mg/gomme',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 140,
            'weight'     => '0.10',
        ],

        /* ══════════════ COSMÉTIQUES (suite) ══════════════ */
        [
            'name'        => 'Huile Corps CBD Relaxante 250mg — 100ml',
            'sku'         => 'GP-HCR-100',
            'price'       => '32.90',
            'sale'        => '27.90',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Huile sèche corps CBD + jojoba + lavande. Peau soyeuse et détendue.",
            'description' =>  "<p>L'huile Corps CBD Relaxante combine 250 mg de CBD Isolat dans une base d'huile de jojoba bio, d'huile d'amande douce et d'huile essentielle de lavande vraie. Huile sèche à absorption rapide, sans résidu gras. Idéale après la douche ou le bain.</p>",
            'cbd_concentration' => '250mg/100ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 85,
            'weight'     => '0.15',
        ],
        [
            'name'        => 'Gel Douche CBD Revitalisant 150mg — 200ml',
            'sku'         => 'GP-GDC-200',
            'price'       => '18.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Gel douche surgras au CBD + aloe vera + huile d\'argan. Formule douce.",
            'description' =>  "<p>Notre Gel Douche CBD Revitalisant est formulé avec 150 mg de CBD Isolat, de l'aloe vera bio (30%), de l'huile d'argan et des extraits de menthe poivrée. pH neutre (5,5), adapté aux peaux sensibles. 100% naturel, sans SLS/SLES.</p>",
            'cbd_concentration' => '150mg/200ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 120,
            'weight'     => '0.30',
        ],
        [
            'name'        => 'Shampoing CBD Anti-Chute 200mg — 200ml',
            'sku'         => 'GP-SCC-200',
            'price'       => '22.90',
            'sale'        => '18.90',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "CBD + biotine + kératine végétale. Fortifie le cheveu et réduit la chute.",
            'description' =>  "<p>Le Shampoing CBD Anti-Chute associe 200 mg de CBD Isolat à de la biotine (3000 µg/dose), de la kératine végétale hydrolysée et de l'extrait de romarin (rosmarinus officinalis). Stimule les follicules pileux et renforce le cheveu de la racine à la pointe. Sans sulfates, sans silicones.</p>",
            'cbd_concentration' => '200mg/200ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 95,
            'weight'     => '0.30',
        ],
        [
            'name'        => 'Baume Lèvres CBD SPF15 — 5g',
            'sku'         => 'GP-BLC-5',
            'price'       => '7.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Stick baume lèvres CBD + beurre de cacao + filtre solaire SPF15.",
            'description' =>  "<p>Le Baume Lèvres CBD protège et nourrit les lèvres avec 50 mg de CBD Isolat, du beurre de cacao certifié fair trade, de la cire de carnauba vegan et un filtre solaire minéral SPF15. Saveur miel-vanille naturelle. Format pratique pour le sac ou la poche.</p>",
            'cbd_concentration' => '50mg/5g',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 200,
            'weight'     => '0.01',
        ],
        [
            'name'        => 'Contour Yeux CBD Liftant 100mg — 15ml',
            'sku'         => 'GP-CEL-15',
            'price'       => '34.90',
            'sale'        => '',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Soin contour yeux CBD + peptides + caféine. Réduit cernes et poches.",
            'description' =>  "<p>Le Contour Yeux CBD Liftant cible les signes de fatigue avec 100 mg de CBD Isolat, un complexe de peptides Matrixyl 3000, de la caféine 5% et de la vitamine K2. Texture gel légère pour la zone périorbitaire délicate. Testé ophtalmologiquement.</p>",
            'cbd_concentration' => '100mg/15ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 60,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Lotion Corps CBD Hydratante 300mg — 150ml',
            'sku'         => 'GP-LCH-150',
            'price'       => '26.90',
            'sale'        => '21.90',
            'cat'         => 'cosmetiques',
            'featured'    => false,
            'short_desc'  =>  "Lotion légère CBD + beurre de karité + niacinamide. 24h d\'hydratation.",
            'description' =>  "<p>La Lotion Corps CBD Hydratante offre 24h d'hydratation grâce à 300 mg de CBD Isolat, du beurre de karité non-raffiné, de la glycérine végétale et de la niacinamide (B3) qui améliore la barrière cutanée. Texture légère non-grasse, parfum naturel fleur de chanvre.</p>",
            'cbd_concentration' => '300mg/150ml',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 %',
            'stock'      => 110,
            'weight'     => '0.25',
        ],

        /* ══════════════ INFUSIONS CBD (suite) ══════════════ */
        [
            'name'        => 'Infusion CBD Digestion Fenouil-Anis — 20 sachets',
            'sku'         => 'GP-IDF-20',
            'price'       => '14.90',
            'sale'        => '',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Fenouil, anis étoilé, mélisse et chanvre CBD. Confort digestif après repas.",
            'description' =>  "<p>L'infusion CBD Digestion allie fenouil bio, anis étoilé, feuilles de mélisse et fleurs de chanvre CBD. Reconnue par la phytothérapie pour ses propriétés carminatives et antispasmodiques. À consommer après les repas.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 170,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Infusion CBD Anti-Oxydant Hibiscus-Grenade — 20 sachets',
            'sku'         => 'GP-IAO-20',
            'price'       => '15.90',
            'sale'        => '',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Hibiscus, grenade, acérola et chanvre CBD. Riche en polyphénols et vitamine C.",
            'description' =>  "<p>L'infusion Anti-Oxydant associe fleurs d'hibiscus, écorce de grenade, baies d'acérola et fleurs de chanvre CBD. Une véritable bombe anti-oxydante froide ou chaude, riche en anthocyanes, polyphénols et vitamine C naturelle.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 145,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Infusion CBD Immunité Échinacea-Gingembre — 20 sachets',
            'sku'         => 'GP-III-20',
            'price'       => '15.90',
            'sale'        => '12.90',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Échinacée, gingembre, thym et chanvre CBD. Défenses naturelles renforcées.",
            'description' =>  "<p>L'infusion CBD Immunité combine échinacée (fleurs et racine), gingembre frais, thym serpolet et fleurs de chanvre CBD. Reconnue pour soutenir les défenses naturelles de l'organisme. Idéale en cure hivernale.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 155,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Infusion CBD Détox Ortie-Pissenlit — 20 sachets',
            'sku'         => 'GP-IDX-20',
            'price'       => '13.90',
            'sale'        => '',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Ortie, pissenlit, chardon-Marie et chanvre CBD. Drainage et détox du foie.",
            'description' =>  "<p>L'infusion CBD Détox associe feuilles d'ortie, racine de pissenlit, graines de chardon-marie (silymarine) et fleurs de chanvre CBD. Connue pour ses propriétés hépato-protectrices et drainantes. En cure de 3 à 4 semaines.</p>",
            'cbd_concentration' => '~50mg/sachet',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 135,
            'weight'     => '0.04',
        ],
        [
            'name'        => 'Mélange Infusion CBD Vrac Relaxant — 50g',
            'sku'         => 'GP-IVR-50',
            'price'       => '18.90',
            'sale'        => '15.90',
            'cat'         => 'infusions-cbd',
            'featured'    => false,
            'short_desc'  =>  "Mélange vrac 50g : camomille, passiflore, chanvre CBD. Économique et écologique.",
            'description' =>  "<p>Notre mélange en vrac 50g associe camomille, passiflore, fleurs de lavande et fleurs de chanvre CBD broyées. Format économique et éco-responsable : moins d'emballage, même qualité. Livré en sachet kraft refermable. Dosage : 2-3g par infusion.</p>",
            'cbd_concentration' => '~50-80mg/dose',
            'cbd_spectrum'      => 'Fleur chanvre',
            'cbd_extraction'    => 'Infusion',
            'cbd_origin'        => 'France Bio',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 120,
            'weight'     => '0.06',
        ],

        /* ══════════════ CAPSULES CBD (suite) ══════════════ */
        [
            'name'        => 'Capsules CBD + Curcuma 10mg — x60',
            'sku'         => 'GP-CCC-60',
            'price'       => '44.90',
            'sale'        => '39.90',
            'cat'         => 'capsules-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 10mg + curcuma BCM-95 + poivre noir. Anti-inflammatoire naturel.",
            'description' =>  "<p>Les capsules CBD + Curcuma combinent 10 mg de CBD Isolat avec 400 mg de curcumine BCM-95 (biodisponibilité améliorée 7x) et 5 mg de pipérine de poivre noir. Un binôme naturel contre l'inflammation chronique. Format 60 capsules pour 2 mois de cure.</p>",
            'cbd_concentration' => '10mg/capsule',
            'cbd_spectrum'      => 'Isolat',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 %',
            'stock'      => 75,
            'weight'     => '0.10',
        ],
        [
            'name'        => 'Capsules CBD Sommeil 15mg + Mélatonine — x30',
            'sku'         => 'GP-CSM-30',
            'price'       => '39.90',
            'sale'        => '',
            'cat'         => 'capsules-cbd',
            'featured'    => true,
            'short_desc'  =>  "CBD 15mg + mélatonine 1mg + valériane + GABA. Endormissement facilité.",
            'description' =>  "<p>Les capsules CBD Sommeil combinent 15 mg de CBD Broad Spectrum avec 1 mg de mélatonine liposomale (absorption 10x), 200 mg d'extrait de valériane titrée et 50 mg de GABA. À prendre 30 minutes avant le coucher. Sans accoutumance.</p>",
            'cbd_concentration' => '15mg/capsule',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'USA (chanvre)',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 80,
            'weight'     => '0.05',
        ],
        [
            'name'        => 'Capsules CBD + Oméga-3 20mg — x30',
            'sku'         => 'GP-COM-30',
            'price'       => '49.90',
            'sale'        => '44.90',
            'cat'         => 'capsules-cbd',
            'featured'    => false,
            'short_desc'  =>  "CBD 20mg + EPA/DHA algues + vitamine D3. Synergie anti-inflammatoire.",
            'description' =>  "<p>Les capsules CBD + Oméga-3 associent 20 mg de CBD Full Spectrum à 500 mg d'oméga-3 EPA/DHA issus d'algues (source vegan), et 25 µg de vitamine D3 végétale. Une formule complète pour la santé cardiovasculaire, cérébrale et articulaire.</p>",
            'cbd_concentration' => '20mg/capsule',
            'cbd_spectrum'      => 'Full Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '< 0,2 %',
            'stock'      => 65,
            'weight'     => '0.06',
        ],
        [
            'name'        => 'Capsules CBG + CBD 15mg — x30',
            'sku'         => 'GP-CCG-30',
            'price'       => '54.90',
            'sale'        => '',
            'cat'         => 'capsules-cbd',
            'featured'    => false,
            'short_desc'  =>  "Synergie CBG 10mg + CBD 5mg par capsule. Focus, clarté, tonus.",
            'description' =>  "<p>Les capsules CBG+CBD 15 mg proposent un ratio CBG:CBD 2:1 pour une synergie nootropique maximale. Le CBG (cannabigérol) est le précurseur de tous les cannabinoïdes et est étudié pour ses effets sur la concentration, l'énergie et le confort digestif.</p>",
            'cbd_concentration' => '15mg (CBG+CBD)',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 55,
            'weight'     => '0.05',
        ],

        /* ══════════════ E-LIQUIDES (suite) ══════════════ */
        [
            'name'        => 'E-liquide CBD 300mg Fraise des Bois — 10ml',
            'sku'         => 'GP-ELS-300',
            'price'       => '12.90',
            'sale'        => '9.90',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "300mg CBD, fraise des bois acidulée et naturelle. Base 50PG/50PG.",
            'description' =>  "<p>L'e-liquide CBD Fraise des Bois 300 mg propose des arômes de fraise sauvage et d'hibiscus avec une légère note acidulée. Idéal pour les débutants en vape CBD. Base 50/50 compatible pod et clearomiseur.</p>",
            'cbd_concentration' => '300mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 220,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 300mg Citron Yuzu — 10ml',
            'sku'         => 'GP-ELC-300',
            'price'       => '12.90',
            'sale'        => '',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "300mg CBD, arôme yuzu japonais et zeste de citron vert. Frais et fruité.",
            'description' =>  "<p>L'e-liquide CBD Citron Yuzu 300 mg est inspiré de l'agrume japonais au parfum unique — entre citron, mandarine et pamplemousse. Arôme naturel, saveur fraîche et légèrement florale. Base 50/50.</p>",
            'cbd_concentration' => '300mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 190,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 600mg Pastèque-Menthe — 10ml',
            'sku'         => 'GP-ELP-600',
            'price'       => '17.90',
            'sale'        => '',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "600mg CBD, pastèque juteuse et menthe fraîche. Saveur estivale.",
            'description' =>  "<p>L'e-liquide CBD Pastèque-Menthe 600 mg offre la fraîcheur d'une pastèque mûre relevée d'une touche de menthe. Un arôme estival et rafraîchissant. Base 70VG/30PG pour une vapeur dense et un hit très doux.</p>",
            'cbd_concentration' => '600mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 160,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 600mg Myrtille Sauvage — 10ml',
            'sku'         => 'GP-ELB-600',
            'price'       => '17.90',
            'sale'        => '14.90',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "600mg CBD, myrtille sauvage et cassis. Arômes de fruits des bois intenses.",
            'description' =>  "<p>L'e-liquide CBD Myrtille Sauvage 600 mg capture les arômes profonds et authentiques des myrtilles et du cassis des Alpes. Un goût de fruits des bois intense et légèrement sucré. Base 70VG/30PG.</p>",
            'cbd_concentration' => '600mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 175,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 1000mg Vanille-Caramel — 10ml',
            'sku'         => 'GP-ELV-1000',
            'price'       => '24.90',
            'sale'        => '',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "Haute dose 1000mg CBD. Vanille de Madagascar et caramel salé beurré.",
            'description' =>  "<p>L'e-liquide CBD Vanille-Caramel 1000 mg est une gourmandise en vapeur. Arômes naturels de vanille de Madagascar et de caramel beurre salé. Haute dose CBD pour vapoteurs expérimentés. Base 70VG/30PG, hit très doux.</p>",
            'cbd_concentration' => '1000mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 130,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'Pack Découverte E-liquides CBD x3 — 30ml',
            'sku'         => 'GP-ELK-3X10',
            'price'       => '44.90',
            'sale'        => '37.90',
            'cat'         => 'e-liquides',
            'featured'    => true,
            'short_desc'  =>  "3 e-liquides 600mg au choix : Fruits Rouges + Menthe + Mangue. -15%.",
            'description' =>  "<p>Le Pack Découverte réunit nos 3 best-sellers en e-liquides CBD 600 mg : Fruits Rouges, Menthe Glaciale et Mangue-Passion. Idéal pour découvrir les saveurs GreenPure CBD ou comme cadeau. Économisez 15% par rapport à l'achat unitaire. Base 70VG/30PG, 0mg nicotine.</p>",
            'cbd_concentration' => '600mg x 3 / 30ml total',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 100,
            'weight'     => '0.10',
        ],

        /* ══════════════ E-LIQUIDES ══════════════ */
        [
            'name'        => 'E-liquide CBD 300mg Natural — 10ml',
            'sku'         => 'GP-ELN-300',
            'price'       => '12.90',
            'sale'        => '',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "E-liquide CBD saveur naturelle chanvre. Base 50PG/50VG. Taux nicotine : 0mg.",
            'description' =>  "<p>Notre e-liquide CBD Natural 300 mg est formulé à base de CBD Broad Spectrum dans une base 50/50 PG/VG. Aucune nicotine, aucun additif. Saveur naturelle de chanvre, compatible tous atomiseurs.</p>",
            'cbd_concentration' => '300mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 200,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 600mg Fruits Rouges — 10ml',
            'sku'         => 'GP-ELF-600',
            'price'       => '17.90',
            'sale'        => '14.90',
            'cat'         => 'e-liquides',
            'featured'    => true,
            'short_desc'  =>  "600mg CBD, arôme fruits rouges naturel. Base 70VG/30PG. Vapeur dense.",
            'description' =>  "<p>L'e-liquide CBD Fruits Rouges 600 mg est notre best-seller vape. Arôme naturel de fraise, framboise et cassis. Base 70VG/30PG pour une vapeur dense et un hit doux.</p>",
            'cbd_concentration' => '600mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 250,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 600mg Menthe Glaciale — 10ml',
            'sku'         => 'GP-ELM-600',
            'price'       => '17.90',
            'sale'        => '',
            'cat'         => 'e-liquides',
            'featured'    => false,
            'short_desc'  =>  "600mg CBD, menthe glacier ultra-fraîche. Base 70VG/30PG.",
            'description' =>  "<p>L'e-liquide CBD Menthe Glaciale 600 mg offre une fraîcheur intense avec de la menthe naturelle et du cristal de menthol. Idéal pour les vapoteurs qui apprécient les saveurs fraîches et propres.</p>",
            'cbd_concentration' => '600mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 180,
            'weight'     => '0.03',
        ],
        [
            'name'        => 'E-liquide CBD 1000mg Mangue-Passion — 10ml',
            'sku'         => 'GP-ELH-1000',
            'price'       => '24.90',
            'sale'        => '19.90',
            'cat'         => 'e-liquides',
            'featured'    => true,
            'short_desc'  =>  "Haute dose 1000mg CBD. Arôme mangue-passion exotique. Base 70VG/30PG.",
            'description' =>  "<p>Le e-liquide CBD Mangue-Passion 1000 mg est notre formule premium haute dose pour les vapoteurs expérimentés. Arôme exotique de mangue Alphonso et fruit de la passion.</p>",
            'cbd_concentration' => '1000mg/10ml',
            'cbd_spectrum'      => 'Broad Spectrum',
            'cbd_extraction'    => 'CO₂ Supercritique',
            'cbd_origin'        => 'France',
            'cbd_thc'           => '0,00 % (ND)',
            'stock'      => 120,
            'weight'     => '0.03',
        ],
    ];

    /* ---- Création des produits WooCommerce ---- */
    foreach ($products as $p) {
        // Éviter les doublons
        $existing_id = wc_get_product_id_by_sku($p['sku']);
        if ($existing_id) continue;

        $product = new WC_Product_Simple();
        $product->set_name($p['name']);
        $product->set_sku($p['sku']);
        $product->set_regular_price($p['price']);
        if (! empty($p['sale'])) {
            $product->set_sale_price($p['sale']);
        }
        $product->set_short_description(wp_kses_post($p['short_desc']));
        $product->set_description(wp_kses_post($p['description']));
        $product->set_status('publish');
        $product->set_catalog_visibility('visible');
        $product->set_featured($p['featured']);
        $product->set_manage_stock(true);
        $product->set_stock_quantity($p['stock']);
        $product->set_stock_status('instock');
        $product->set_weight($p['weight']);
        $product->set_reviews_allowed(true);

        // Catégorie
        if (! empty($cat_ids[$p['cat']])) {
            $product->set_category_ids([$cat_ids[$p['cat']]]);
        }

        $product_id = $product->save();

        // Métas CBD
        if ($product_id) {
            update_post_meta($product_id, '_cbd_concentration', $p['cbd_concentration']);
            update_post_meta($product_id, '_cbd_spectrum',      $p['cbd_spectrum']);
            update_post_meta($product_id, '_cbd_extraction',    $p['cbd_extraction']);
            update_post_meta($product_id, '_cbd_origin',        $p['cbd_origin']);
            update_post_meta($product_id, '_cbd_thc',           $p['cbd_thc']);
        }
    }

    // Vider les caches WooCommerce
    wc_delete_product_transients();

    do_action('greenpure_demo_installed');
}
